### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [ngthduy90/TipCalculator#1]
### Overall
- Thanks Nguyen Duy for your submission. I see that you really enjoy the prework :smile:
- You did very great job by implementing all require, optional and additional features. Specially, I love the way you implement animations and the custom numeric keyboard.
- How many years did you work on iOS stuffs? You know a lot of things through TipCalculator.

### Review
- I am appreciate that you know a list of iOS components:
	- CocoaPod
	- AutoLayout
	- Custom view with `.xib` file and `@IBInspectable`
	- Delegation
	- ...

- Why did you put a lot of spacing between line?
- Why didn't you use loop in this case?

```
	btn0.actionType = ActionType.chooseText("0")
	btn0.delegate = self
	listButtons.append(btn0)
        
	btn1.actionType = ActionType.chooseText("1")
	btn1.delegate = self
	listButtons.append(btn1)
        
	btn2.actionType = ActionType.chooseText("2")
	btn2.delegate = self
	listButtons.append(btn2)
	
	...
```

**Comment by ngthduy90** [comment]
@coderschoolreview Thanks for your response. I'm joy when seeing your comment.

> Why did you put a lot of spacing between line?

Hmmm, It's related to my habbit and easy to read the code. I set font size small and if they are too close, I feel stress haha. When works in team, I follow code convetion of team.

> Why didn't you use loop in this case?

This keyboard took me a lots of time. First time, I set button from zero to nine is number, not text. But while implementing, I got some problem between number and text, so that I changed to text quickly and tried to finish pre-work firstly.

In this pre-work, I need to refactor code. Currently, I think It's acceptable. Not too bad, huh? 😄

> How many years did you work on iOS stuffs?

I have worked on Objective-C for a year (native projects are 5 months, the rest is hybrid). I've just learnt Swift a week before applying CoderSchool. Your pre-work gives me motivation alots.

Thank you again for reviewing my pre-work project.

**Comment by coderschoolreview** [comment]
>This keyboard took me a lots of time. First time, I set button from zero to nine is number, not text. But while implementing, I got some problem between number and text, so that I changed to text quickly and tried to finish pre-work firstly.

I really appreciate, but as you know we can do the lazy way by using numeric keyboard by default :rocket:

>In this pre-work, I need to refactor code. Currently, I think It's acceptable. Not too bad, huh?

Haha, your code is super good :smile: About the spacing I think that the common things is just blocking all relate function (line of code) into a block. Should not separate each line of code by spacing them.

**Comment by ngthduy90** [comment]
@coderschoolreview 😁 Today is a wonderful day. I get an invitation from CoderSchool and a nice compliment from you.

We could use a default numberic keyboard but... I think I need to do something cool for impression 🤗 and learn more thing from Swift.

I will try to block all related functions and reduce the spacing. Thanks a lot. You make my day.
